### ISSUE TITLE
Desarrollar componente entidad-fieldset

### ISSUE THREAD

**Issue by ivancas84** [ivancas84/organize-angular#7]
* [x] [Analizar autocompletar de materia.angular](https://github.com/ivancas84/angular-core-md/issues/7)
* [x] [Desarrollar custom form control para implementar autocompletar](https://github.com/ivancas84/angular-core-md/issues/8)
* [x] [Refactorizar componente autocompletar para definir la misma funcionalidad del proyecto angular-core](https://github.com/ivancas84/angular-core-md/issues/9)
* [x] Definir autocompletar de campo sistema
* [x] Incorporar autocompletar a angular-gen-md
